services:
  web:
    build: .
    ports:
      - '8000:8000'
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
  db:
    image: sqlite3
    volumes:
      - sqlite3_data:/var/lib/sqlite3/data
    environment:
      - "SQLITE_HOST_AUTH_METHOD=trust"

volumes:
  sqlite3_data: